name: Video Quality Tests
on:
  workflow_dispatch:
jobs:
  run-video-quality-tests:
    name: Run Video Quality Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: pr-branch
      - name: Checkout Base Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base-branch
      - name: Move base-branch Files to pr-diffs
        run: |
          mkdir -p pr-diffs/${{ github.event.inputs.pr_number }}
          cp -r base-branch/* pr-diffs/${{ github.event.inputs.pr_number }}/
      - name: Upload HTML Comparison Page
        uses: actions/upload-artifact@v4
        with:
          name: video-comparison-page
          path: pr-diffs/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./pr-diffs/${{ github.event.pull_request.number }}

      - name: Comment PR with Link to Diff Report
        uses: mshick/add-pr-comment@v2
        with:
          message: "📊 [View the Evaluation Diff Report](https://GeekyBecky.github.io/Video_Comparison_Tool/pr-diffs/${{ github.event.pull_request.number }}/index.html)"