name: Video Quality Tests
on:
  workflow_dispatch:
jobs:
  run-video-quality-tests:
    name: Run Video Quality Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: pr-branch
      - name: Checkout Base Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base-branch
      - name: Install Dependencies
        run: |
          pip install google-cloud-storage
      - name: Run Python Script to Generate HTML
        env:
          GCS_SIGNEDURL_KEY: ${{ secrets.GCS_SIGNEDURL_KEY }}
        run: |
          runId=${{ github.run_id }}
          python pr-branch/generate_html.py "$runId"
      - name: Move pr-branch Files to pr-diffs
        run: |
          runId=${{ github.run_id }}
          mkdir -p pr-diffs/${runId}
          rsync -av --exclude=".git" pr-branch/ pr-diffs/${runId}/
          find pr-diffs/${runId}/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pr-diffs/${{ github.run_id }}
          destination_dir: ./pr-diffs/${{ github.run_id }}

      - name: Print Report Link
        run: |
          runId=${{ github.run_id }}
          echo "📊 [View the Evaluation Diff Report](https://GeekyBecky.github.io/Video_Comparison_Tool/pr-diffs/${runId}/index.html)"
